/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "sfbdjfnvthlhjjvpwlui"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmYmRqZm52dGhsaGpqdnB3bHVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxMzk5NzUsImV4cCI6MjA3NzcxNTk3NX0.lslAYeD-c-6M3WfM1waXefAQrTUAQU3bLXawxWYCMqg"